name: newsrag-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.1=hf5d6505_1
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=h0159041_2_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h2c6b04d_3
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - babel==2.17.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - courlan==1.3.2
      - dateparser==1.2.2
      - feedparser==6.0.12
      - htmldate==1.9.4
      - justext==3.0.2
      - lxml==6.0.2
      - lxml-html-clean==0.4.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.11.3
      - sgmllib3k==1.0.0
      - six==1.17.0
      - tld==0.13.1
      - trafilatura==2.0.0
      - tzdata==2025.3
      - tzlocal==5.3.1
      - urllib3==2.6.2